MARKET_SNAPSHOTS = "market.snapshots"
FEATURE_SNAPSHOTS = "features.snapshots"
DECISION_CONTEXTS = "strategy.decision_context"
BASELINE_ASSESSMENTS = "strategy.baseline_assessment"
AI_ASSESSMENTS = "strategy.ai_assessment"
POSITION_TARGETS = "strategy.position_target"
POLICY_DECISIONS = "policy.decisions"
RISK_DECISIONS = "risk.decisions"
ORDER_INTENTS = "execution.order_intents"
ORDER_UPDATES = "execution.order_updates"
FILL_EVENTS = "execution.fill_events"
PORTFOLIO_SNAPSHOTS = "portfolio.snapshots"
RECONCILIATION_REPORTS = "reconciliation.reports"
AUDIT_RECORDS = "system.audit_records"

