"""Internal, non-promotable derivatives backtest domain primitives.

LF-B1.1 exposes only strict contracts and pure Decimal accounting.  It has no
event source, publisher, CLI, database, workflow, or live-runtime integration.
"""

from .accounting import (
    DerivativesAccountingError,
    account_equity,
    conservative_liquidation_price,
    contract_face_value,
    fee_amount_for_role,
    forced_close_cost,
    forced_close_rate,
    funding_payment,
    initial_margin_rate,
    initial_margin_required,
    is_liquidatable,
    isolated_equity,
    isolated_free_collateral,
    liquidation_requirement,
    maintenance_margin_required,
    net_pnl,
    opening_account_state,
    quote_notional,
    raw_liquidation_price,
    realized_pnl,
    signed_base_exposure,
    unrealized_pnl,
)
from .contracts import (
    DERIVATIVES_BACKTEST_ACCOUNTING_POLICY_ID,
    DERIVATIVES_BACKTEST_FAMILY,
    DERIVATIVES_BACKTEST_FEE_RATE_UNIT,
    DERIVATIVES_BACKTEST_SCHEMA_VERSION,
    DERIVATIVES_BACKTEST_SYMBOL,
    DERIVATIVES_BACKTEST_TIMEFRAME,
    DerivativesBacktestContractError,
    DerivativesBacktestScopeV1,
    ExecutionFeeScheduleV1,
    FundingRateScheduleV1,
    IsolatedAccountStateV1,
    LinearPerpetualContractV1,
    LiquidityRoleV1,
    MarginModeV1,
    OpeningAccountStateV1,
    PositionModeV1,
    PositionSideV1,
    PositionStateV1,
    PositionTierV1,
    canonical_accounting_decimal,
    parse_canonical_accounting_decimal,
    validate_v1_instrument_contract,
)


__all__ = [
    "DERIVATIVES_BACKTEST_ACCOUNTING_POLICY_ID",
    "DERIVATIVES_BACKTEST_FAMILY",
    "DERIVATIVES_BACKTEST_FEE_RATE_UNIT",
    "DERIVATIVES_BACKTEST_SCHEMA_VERSION",
    "DERIVATIVES_BACKTEST_SYMBOL",
    "DERIVATIVES_BACKTEST_TIMEFRAME",
    "DerivativesAccountingError",
    "DerivativesBacktestContractError",
    "DerivativesBacktestScopeV1",
    "ExecutionFeeScheduleV1",
    "FundingRateScheduleV1",
    "IsolatedAccountStateV1",
    "LinearPerpetualContractV1",
    "LiquidityRoleV1",
    "MarginModeV1",
    "OpeningAccountStateV1",
    "PositionModeV1",
    "PositionSideV1",
    "PositionStateV1",
    "PositionTierV1",
    "account_equity",
    "canonical_accounting_decimal",
    "parse_canonical_accounting_decimal",
    "conservative_liquidation_price",
    "contract_face_value",
    "fee_amount_for_role",
    "forced_close_cost",
    "forced_close_rate",
    "funding_payment",
    "initial_margin_rate",
    "initial_margin_required",
    "is_liquidatable",
    "isolated_equity",
    "isolated_free_collateral",
    "liquidation_requirement",
    "maintenance_margin_required",
    "net_pnl",
    "opening_account_state",
    "quote_notional",
    "raw_liquidation_price",
    "realized_pnl",
    "signed_base_exposure",
    "unrealized_pnl",
    "validate_v1_instrument_contract",
]
